# Generated by Django 3.1.4 on 2020-12-28 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Course Attachment',
                'verbose_name_plural': 'Course Attachments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('to_dt', models.DateTimeField(verbose_name='Deadline')),
                ('from_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Project Requirement',
                'verbose_name_plural': 'Project Requirements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Teacher',
                'verbose_name_plural': 'Course Teachers',
                'managed': True,
            },
        ),
    ]
