# Generated by Django 3.1.4 on 2021-02-19 07:19

import core.utils.invitations
from django.contrib.postgres.operations import CITextExtension
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('code', django.contrib.postgres.fields.citext.CICharField(max_length=10, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Course Attachment',
                'verbose_name_plural': 'Course Attachments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.utils.invitations.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=30)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('type', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=30)),
            ],
            options={
                'verbose_name': 'Course Invitation',
                'verbose_name_plural': 'Course Invitations',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Course Student',
                'verbose_name_plural': 'Course Students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Course Teacher',
                'verbose_name_plural': 'Course Teachers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', django.contrib.postgres.fields.citext.CICharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('to_dt', models.DateTimeField(verbose_name='Deadline')),
                ('from_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start date')),
            ],
            options={
                'verbose_name': 'Project Requirement',
                'verbose_name_plural': 'Project Requirements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Project Requirement Attachment',
                'verbose_name_plural': 'Project Requirement Attachments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.utils.invitations.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=30)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Team Student',
                'verbose_name_plural': 'Team Students',
                'managed': True,
            },
        ),
    ]
