# Generated by Django 3.1.4 on 2021-01-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.teacher', to_field='uid'),
        ),
        migrations.AddField(
            model_name='courseattachment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.course', to_field='uid'),
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', to_field='uid'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together={('title', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('teacher', 'course')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner'], name='courses_cou_owner_i_f32810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('owner', 'code')},
        ),
    ]
