# Generated by Django 3.1.4 on 2021-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210220_0354'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_owner_i_f32810_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='courses_tea_require_bc3ffe_idx',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner'], name='course_owner_index'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['requirement'], name='team_requirement_index'),
        ),
    ]
