# Generated by Django 3.1.4 on 2021-02-18 21:09

import core.utils.invitation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20210216_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.utils.invitation.generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=30)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='courseinvitation',
            name='expiry_date_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='courseinvitation',
            name='unique_course_invitation',
        ),
        migrations.AlterField(
            model_name='courseinvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='courseinvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AddConstraint(
            model_name='courseinvitation',
            constraint=models.CheckConstraint(check=models.Q(created_at__lte=django.db.models.expressions.F('expiry_date')), name='courseinvitation_expiry_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='courseinvitation',
            constraint=models.UniqueConstraint(fields=('email', 'course'), name='unique_course_invitation'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='courses.team', to_field='uid'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.CheckConstraint(check=models.Q(created_at__lte=django.db.models.expressions.F('expiry_date')), name='teaminvitation_expiry_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(fields=('email', 'team'), name='unique_team_invitation'),
        ),
    ]
