# Generated by Django 3.1.4 on 2021-05-19 17:32

import courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20210402_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequirement',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message="Total marks can't be zero or below.")], verbose_name='Total Marks'),
        ),
        migrations.CreateModel(
            name='ProjectRequirementGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=-1, message="Marks can't be below zero.")], verbose_name='Marks')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.projectrequirement', to_field='uid')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, to_field='uid')),
            ],
            options={
                'verbose_name': 'Project Requirement Grade',
                'verbose_name_plural': 'Project Requirement Grades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('project_zip', models.FileField(upload_to=courses.models._project_upload_path, verbose_name='Project Compressed file')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.team', to_field='uid')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='projectrequirementgrade',
            index=models.Index(fields=['requirement'], name='projectrequirementgrade_index'),
        ),
        migrations.AddConstraint(
            model_name='projectrequirementgrade',
            constraint=models.UniqueConstraint(fields=('student', 'requirement'), name='unique_requirement_grade'),
        ),
    ]
