# Generated by Django 3.1.4 on 2021-02-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210218_2109'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseinvitation',
            name='unique_course_invitation',
        ),
        migrations.RemoveConstraint(
            model_name='teaminvitation',
            name='unique_team_invitation',
        ),
    ]
