version: "3"

volumes:
  local_postgres_data: {}

services:
  peam_backend:
    image: peam_backend:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: peam_backend
    command: ./docker/.dev/start.sh
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - DJANGO_DEBUG=True
      - DATABASE_URL="postgres://username:password@postgres:5432/peam_backend"
    volumes:
      - .:/app

  postgres:
    image: postgres:12.3
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=peam_backend
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
