version: "3"

volumes:
  local_postgres_data: {}

services:
  peam_backend:
    image: peam_backend:prod
    container_name: peam_backend
    command: ./docker/.prod/start.sh
    restart: always
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=settings.prod
      - DJANGO_DEBUG=False
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: postgres:12.3
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
