version: "3"

volumes:
  local_postgres_data:
    external: false
  media:
    external: false

services:
  peam_backend:
    image: peam_backend:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: peam_backend
    command: ./docker/.dev/start.sh
    ports:
      - 8000:8000
    env_file:
      - ./docker/.dev/.env.dev
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    container_name: postgres
    ports:
      - "127.0.0.1:5243:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./docker/.dev/.env.dev.postgres
