version: "3"

volumes:
  local_postgres_data:
    external: false
  media:
    external: false

services:
  peam_backend:
    image: peam_backend:prod
    container_name: peam_backend
    command: ./docker/.prod/start.sh
    restart: always
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - JWT_KEY=${JWT_KET}
      - DJANGO_DEBUG=False
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - media:/app/media

  postgres:
    image: postgres:12.3
    container_name: postgres
    ports:
      - "127.0.0.1:5342:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
