version: "3"

volumes:
  local_postgres_data:
    external: false
  media:
    external: false

services:
  peam_backend:
    image: peam_backend:prod
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
    container_name: peam_backend
    command: ./docker/.prod/start.sh
    restart: always
    ports:
      - 8000:8000
    environment:
      - DJANGO_JWT_KEY=${DJANGO_JWT_KEY}
      - DJANGO_JWT_VERIFY_KEY=${DJANGO_JWT_VERIFY_KEY}
    env_file:
      - ./docker/.prod/.env.prod
    volumes:
      - media:/app/media

  postgres:
    image: postgres:12.3
    container_name: postgres
    restart: always
    ports:
      - "127.0.0.1:5342:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./docker/.prod/.env.prod.postgres
