version: "3"

services:
  peam_backend:
    image: peam_backend:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    container_name: peam_backend
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    volumes:
      - ..:/app