# Generated by Django 3.1.4 on 2021-05-18 17:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210220_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models._avatar_upload_path, verbose_name='Profile Picture'),
        ),
    ]
