# Generated by Django 3.1.4 on 2021-01-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('courses', '0002_auto_20210102_2319'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='users.student', to_field='uid'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='projects.team', to_field='uid'),
        ),
        migrations.AddField(
            model_name='team',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.projectrequirement', to_field='uid'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('student', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'requirement')},
        ),
    ]
