name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8 src --config=setup.cfg

  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Build the Stack
        run:  make COMPOSE_FILE="docker-compose.ci.yml" build

      - name: Running DB
        run:  make COMPOSE_FILE="docker-compose.ci.yml" db

      - name: Make DB Migrations
        run:  make COMPOSE_FILE="docker-compose.ci.yml" migrate

      - name: Run Django Tests
        run:  make COMPOSE_FILE="docker-compose.ci.yml" test